name: test-application
on:
  pull_request:
    branches:
      v1
jobs:
  Test:
    name: 
    runs-on: ubuntu-latest
    steps:
      - name: check-out-current-repository  
        uses: actions/checkout@v4
      - run: echo "RUNNING TESTS"
      - run: python -m pip install --upgrade pip && pip3 install pytest 
      - run: pip3 install -r ./requirements.txt
      - run: python3 -m pytest
